### PR TITLE
Migrate CI to GH Actions

### PR DESCRIPTION
**Pull request by leifmadsen**

### CODE REVIEW

**Comment by leifmadsen** [comment]
@JoanneOFlynn2018 btw this is the change I needed to land before working on that auto-build documentation / presentation for you. I'm unblocked now :)

**Review by elfiesmelfie — APPROVED** [review]
Looks good, and your approach (i.e. fedora container and a script rather than custom action) might get stolen for my RPM builds for collectd-/qdr-config when I get back to that work.

**Comment by leifmadsen** [comment]
> Looks good, and your approach (i.e. fedora container and a script rather than custom action) might get stolen for my RPM builds for collectd-/qdr-config when I get back to that work.

This is basically how I was doing things in Travis-CI as well, so it's somewhat portable, which is nice. For your RPM work, I'd totally do the Fedora base image and run scripts there. That way you can easily install `mock` and run 2 simple commands that will result in an SRPM from the spec file, and then a full RPM from the SRPM input.

That was always the pattern I followed when needing to build RPMs since it runs in a chroot and .... actually right, that's why I wasn't using `mock` any more... it seems to fail when running in a container.

Anyways, easy enough to install `rpmbuild` you just don't get the dependency management and checks for spec defining the packages. Worth another try though, I haven't tried in a long time.

**Comment by leifmadsen** [comment]
I checked `master` after this was merged and verified that a new build commit was pushed. Also reviewed the CI log and that also looks good.

**Comment by leifmadsen** [comment]
[Migrate from Travis-CI to GitHub Actions](https://trello.com/c/QVFdw42L/1210-migrate-from-travis-ci-to-github-actions)

**Pull request merged**
