### PR TITLE
Reduce the number of Ceilometer pollsters

### PR DESCRIPTION
**Pull request by leifmadsen**
Reduce the number of Ceilometer pollsters to only those used by the
sample STF dashboards.

Closes: rhbz#2239390

### CODE REVIEW

**Review by yadneshk — COMMENTED** [review]
Should we document these pollsters else where as optional meters ?

**Comment by jlarriba** [comment]
It would make sense to align this pollsters to what we are using as default for RHOSP18, which is kind of similar to the one proposed here (at least for computes). 

I propose that we make them identical as 
https://github.com/openstack-k8s-operators/telemetry-operator/blob/main/templates/ceilometercentral/config/polling.yaml for control plane and
https://github.com/openstack-k8s-operators/telemetry-operator/blob/main/templates/ceilometercompute/config/polling.yaml for compute.

**Comment by leifmadsen** [comment]
> Should we document these pollsters else where as optional meters ?

It would be ideal that Ceilometer has documentation for all the available pollsters, but that's out of scope for this task

**Review by yadneshk — APPROVED** [review]

**Comment by leifmadsen** [comment]
I've verified that the dashboards continue to work with only these pollsters enabled for STF 1.5 and have provided a documentation changes item in Jira for release to note that this was updated.

**Pull request merged**
