### PR TITLE
Migrate to CatalogSource vs OperatorSource

### PR DESCRIPTION
**Pull request by leifmadsen**

### CODE REVIEW

**Comment by leifmadsen** [comment]
I'm working on migrating to bundles and catalogsources vs operatorsources. This is marked as a draft until I can do the downstream migration.

Not entirely sure how that is going to look yet. I have some reading to do to see if we can maybe use some more official paths vs our own managed infra.

**Comment by leifmadsen** [comment]
[Migrate Operators to bundle packaging format and distribution](https://trello.com/c/xfwIfs7Z/1065-migrate-operators-to-bundle-packaging-format-and-distribution)

**Comment by leifmadsen** [comment]
This is ready for review now that I've migrated everything over and tested. These instructions now work for the current STF 1.0 release, so can be merged to master. Works for both upstream and downstream. Can be imported to downstream if warranted.

**Review by JoanneOFlynn2018 — APPROVED** [review]
Looks good to me!

**Pull request merged**
